server:
  port: 9091 #用户微服务端口
eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:9080/eureka/,http://127.0.0.1:8090/eureka/
spring:
  application:
    name: user-service  #微服务名称
feign:
  hystrix:
    enabled: true  # 开启服务降级功能  必须开启否则会报错而且调用不了降级方法
girlname: marry
